#!/usr/bin/env python3
"""
gen_disasm_jumptables.py — extract PC-indexed jump tables from an AS .lst
listing. Emits a TOML discovery file with `[[jump_table]]` records plus a
`[functions].extra` array for every reachable target.

Reads:   <disasm>/<game>.lst
         segagenesisrecomp/tests/fixtures/<game>/l1/code_addresses.txt
Writes:  segagenesisrecomp/<game>/<prefix>.disasm_jumptables.toml

The recompiler discovers PC-indexed JMPs by scanning instructions, but
without static enumeration it cannot follow them past the dispatch site.
Each "unresolved" PC-indexed jump table is a discovery hole. Disasms
encode jump tables as one of two shapes; we extract both:

    PCREL_W :  <Base>:
                   dc.w  Target_0 - <Base>
                   dc.w  Target_1 - <Base>
                   ...

    ABS_L   :  <Base>:
                   dc.l  Target_0
                   dc.l  Target_1
                   ...

Detection walks the listing row-by-row. A run becomes a jump table when
2+ consecutive entries at consecutive addresses (stride 2 for PCREL_W,
stride 4 for ABS_L) all resolve to in-ROM, even, code addresses (per the
L1 code_addresses fixture). Each emitted directive carries the start,
end (exclusive), stride and format — the recompiler honors these
verbatim, no additional inference required.

The strict code-address filter is what separates jump tables from the
many other dc.l/dc.w runs in a disasm (sprite mappings, art/PLC
pointers, level layouts, palette tables). Data tables fail validation
because their targets land in non-code regions or address 0.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT      = Path(__file__).resolve().parents[5]
SUBMODULE_ROOT = Path(__file__).resolve().parents[2]

LST_PATH       = REPO_ROOT / "_s1disasm" / "sonic.lst"
CODE_ADDR_PATH = SUBMODULE_ROOT / "tests" / "fixtures" / "sonic1" / "l1" / "code_addresses.txt"
OUT_PATH       = SUBMODULE_ROOT / "sonicthehedgehog" / "sonic1.disasm_jumptables.toml"

HEADER_DEFAULT = (
    "# {prefix}.disasm_jumptables.toml — auto-generated by\n"
    "# tests/tools/gen_disasm_jumptables.py.\n"
    "#\n"
    "# Every PC-indexed jump table found by walking the disasm .lst.\n"
    "# Each table is one [[jump_table]] record; every reachable target\n"
    "# (table entry, plus the bra-trampoline destination if applicable)\n"
    "# is added to [functions].extra. Reference this file from game.toml:\n"
    "#\n"
    "#   [game]\n"
    "#   discovery_files = [\"{prefix}.disasm_jumptables.toml\"]\n"
    "\n"
)

# Match a primary listing row:
#   "[ (N) ]  LINE_NO/  ADDR : REST"
# The optional leading `(N)` is AS's include-nesting / sub-pass prefix. Whether
# we CONSUME `(N)` rows depends on the discovery mode (set in main):
#
#  * Fixture mode (--code-addrs given; S1/S2): `(N)` rows ARE consumed. S1/S2
#    keep almost all code — and therefore almost all jump tables — in `include`d
#    files, so those rows are ALL `(N)`-prefixed; rejecting them made the
#    extractor find 42 targets instead of 1010 (the regression this guards).
#    Their targets are validated against a 68K-only fixture, so the macro/Z80
#    re-listings can't contaminate.
#
#  * Derived mode (no --code-addrs; S3/S&K): `(N)` rows are SKIPPED entirely.
#    skdisasm re-lists the same address under both a `(N)` macro/include pass
#    AND its real non-prefixed pass, and embeds a Z80 driver in `(N)` rows with
#    its own address space. Consuming `(N)` rows here mis-bounds tables over
#    real code (data-izing functions -> "JSR target not in func table" ->
#    dispatch misses). S3's jump tables all live in non-`(N)` code, so skipping
#    `(N)` is both correct and the original (pre-regression) behavior.
#
# The prefix is captured as group 1 so main() can apply the mode gate.
LINE_RE = re.compile(
    r"^(\(\d+\)\s+)?\s*\d+/\s+([0-9A-Fa-f]+)\s*:\s*(.*)$"
)
# First-emit-is-data classifier — used to derive the code-address set from
# the .lst when no --code-addrs fixture is supplied.
DATA_DIRECTIVE_RE = re.compile(r"^(?:dc\.[bwl]|dcb\.[bwl]|ds\.[bwl]|"
                               r"binclude|incbin|even|align|cnop|org)\b",
                               re.IGNORECASE)

# Source patterns we recognize as jump-table entries. The optional
# leading "Label:" (or "Label1:Label2:...") covers tables whose base
# label is pinned inline with the first entry, e.g.
#   VBlank_Index: dc.w VBlank_Lag-VBlank_Index
# AS-flavor anonymous labels (`+`, `-`, `++`, etc.) appear at multiple
# offsets in the listing for nameless temporary jump targets. The first
# captured group is the entry's named target; we permit `+`/`-` runs as
# valid operands so single-entry PCREL_W tables that point at an
# anonymous label still get extracted.
LBL_NAME = r"(?:[A-Za-z_.][\w.]*|[+\-]+)"

PCREL_W_RE = re.compile(
    r"^\s*(?:[A-Za-z_][\w.]*\s*:\s*)*"
    r"dc\.w\s+(" + LBL_NAME + r")\s*-\s*(" + LBL_NAME + r")\s*(?:;.*)?$"
)
ABS_L_RE = re.compile(
    r"^\s*(?:[A-Za-z_][\w.]*\s*:\s*)*"
    r"dc\.l\s+(" + LBL_NAME + r")\s*(?:;.*)?$"
)
# bra.w / bra.s trampoline-table form. Each entry is a single 68K
# instruction (`bra.w Target` = 4 bytes 60 00 XX XX, or `bra.s Target`
# = 2 bytes 60 XX) at the table address. The dispatcher does
# `JMP/JSR Table(pc,Dn.W)` and lands on the trampoline, which then
# branches on to the real handler. Each entry's ADDRESS is therefore
# itself a function entry point; the extractor emits an extra_func
# for each. Sonic 2's GameModesArray ($003A2) and Sonic 1's
# EniDec_JmpTable ($1852) are the canonical examples.
BRA_W_RE = re.compile(
    r"^\s*(?:[A-Za-z_][\w.]*\s*:\s*)*"
    r"bra\.w\s+(" + LBL_NAME + r")\s*(?:;.*)?$"
)
BRA_S_RE = re.compile(
    r"^\s*(?:[A-Za-z_][\w.]*\s*:\s*)*"
    r"bra(?:\.s)?\s+(" + LBL_NAME + r")\s*(?:;.*)?$"
)

# Labels pinned to the current address. AS produces several forms in
# the listing depending on how the label was declared:
#   - "Name:"                       — standard, may be inline before code
#   - "Name label *"                — AS pseudo-op, also pins to *
#   - "name := target"              — alias, may need indirection
# Equate marker rows look like "=$NNNN     <label-form> ...", so we
# match anywhere in the source rather than anchoring to the start.
LABEL_INLINE_RE = re.compile(
    r"(?<![\w.])([A-Za-z_][\w.]*)\s*:(?!=)"
)
LABEL_DECL_RE = re.compile(
    r"(?<![\w.])([A-Za-z_][\w.]*)\s+label\s+\*"
)
ALIAS_RE = re.compile(
    r"(?<![\w.])([A-Za-z_][\w.]*)\s*:=\s*([A-Za-z_][\w.]*)"
)


def parse_emit_row(rest: str):
    """
    Given the post-':' portion of a listing row, return
    (bytes_hex_list, source_text) when the row emits bytes, else
    (None, source_text). Macro and equate marker rows return
    (None, rest).
    """
    if not rest:
        return None, ""
    # Macro/equate markers don't emit a fresh byte run we want.
    if rest.startswith("(MACRO") or rest.startswith("="):
        return None, rest
    # Consume the leading run of whitespace-delimited 4-hex-char byte
    # tokens, tracking position so the source tail can be sliced directly.
    # (Re-joining the tokens and calling rest.index() is fragile — it
    # assumes single-space separators, which the skdisasm/asl listing does
    # not always use, and raised ValueError on tab/multi-space runs.)
    bytes_hex: list[str] = []
    pos = 0
    while True:
        m = re.match(r"\s*([0-9A-Fa-f]{4})(?=\s|$)", rest[pos:])
        if not m:
            break
        bytes_hex.append(m.group(1))
        pos += m.end()
    if not bytes_hex:
        return None, rest
    return bytes_hex, rest[pos:].lstrip()


def load_code_addrs(path: Path) -> set[int]:
    out: set[int] = set()
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            out.add(int(line, 16))
        except ValueError:
            pass
    return out


def signed_w(b_hi: int, b_lo: int) -> int:
    v = (b_hi << 8) | b_lo
    return v - 0x10000 if v & 0x8000 else v


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lst", type=Path, default=LST_PATH,
                    help="AS .lst listing produced by the disasm build")
    ap.add_argument("--code-addrs", type=Path, default=None,
                    help="optional code_addresses.txt fixture (from "
                         "gen_l1_fixtures.py). If omitted, the code-address "
                         "set is derived from the .lst itself (first-emit-is-"
                         "instruction) — no runtime fixture needed.")
    ap.add_argument("-o", "--output", type=Path, default=OUT_PATH,
                    help="output .disasm_jumptables.txt")
    ap.add_argument("--prefix", type=str, default="sonic1",
                    help="cfg output_prefix; appears in the file header")
    ap.add_argument("--rom-max", type=lambda s: int(s, 0), default=0x400000,
                    help="reject RAW targets >= this address, before --offset "
                         "(default 0x400000). For a 2 MB half pass 0x200000.")
    ap.add_argument("--offset", type=lambda s: int(s, 0), default=0,
                    help="absolute offset added to every emitted table "
                         "start/end and target (default 0). The .lst is "
                         "walked in raw 0-based space; --offset relocates the "
                         "result for lock-on / multi-ROM builds (Sonic 3 "
                         "locked onto S&K maps to 0x200000).")
    ap.add_argument("--header", type=str, default=None,
                    help="override the file's header comment")
    ap.add_argument("--min-entries", type=int, default=2,
                    help="minimum entries to qualify as a jump table. "
                         "Per-entry validation (target in code_addresses, "
                         "even, in-rom) is the safety net for false "
                         "positives within an accepted run; this gate "
                         "prevents single isolated bra.s/bra.w "
                         "instructions outside any table from being "
                         "misclassified as 1-entry tables.")
    args = ap.parse_args()

    if not args.lst.exists():
        print(f"missing: {args.lst}", file=sys.stderr); return 2

    fixture_code_addrs: set[int] | None = None
    if args.code_addrs is not None:
        if not args.code_addrs.exists():
            print(f"missing: {args.code_addrs}", file=sys.stderr); return 2
        fixture_code_addrs = load_code_addrs(args.code_addrs)
        if not fixture_code_addrs:
            print(f"empty: {args.code_addrs}", file=sys.stderr); return 2

    # Consume AS `(N)` sub-pass rows only in fixture mode (S1/S2, whose tables
    # live in include files). In derived mode (S3/S&K) skip them — see LINE_RE.
    consume_subpass = fixture_code_addrs is not None

    # ----- Pass 1: collect all labels, aliases, and emit rows ----------
    label_addr: dict[str, int] = {}
    aliases:    dict[str, str] = {}
    rows: list[tuple[int, list[str] | None, str]] = []  # (addr, bytes_or_none, source)
    # Derived code-address set (first-emit-is-instruction per offset), used
    # when no --code-addrs fixture is supplied.
    derived_code: set[int] = set()
    derived_data: set[int] = set()

    for raw in args.lst.read_text(encoding="utf-8", errors="replace").splitlines():
        m = LINE_RE.match(raw)
        if not m:
            continue
        try:
            addr = int(m.group(2), 16)
        except ValueError:
            continue
        is_subpass = m.group(1) is not None
        # Derived mode (no fixture, S3/S&K): skip `(N)` rows entirely so macro/
        # include re-listings and the embedded Z80 driver can't be scanned for
        # tables or pollute the derived code set (see LINE_RE comment). Fixture
        # mode (S1/S2) consumes them — their tables live in includes.
        if is_subpass and not consume_subpass:
            continue
        rest = m.group(3)
        bytes_hex, source = parse_emit_row(rest)

        # Build the DERIVED code-address set (used only when no --code-addrs
        # fixture is supplied). In derived mode `(N)` rows were already skipped
        # above, so everything here is a real non-prefixed 68K emit.
        if (bytes_hex is not None
                and addr not in derived_code and addr not in derived_data):
            if DATA_DIRECTIVE_RE.match(source):
                derived_data.add(addr)
            else:
                derived_code.add(addr)

        # Capture every label form anywhere in the row. AS prints
        # equate markers as "=$NNNN  Name label *" / "=$NNNN  alias :=
        # target", so anchored matches miss them — we search instead.
        for mm in LABEL_INLINE_RE.finditer(rest):
            label_addr.setdefault(mm.group(1), addr)
        for mm in LABEL_DECL_RE.finditer(rest):
            label_addr.setdefault(mm.group(1), addr)
        for mm in ALIAS_RE.finditer(rest):
            aliases.setdefault(mm.group(1), mm.group(2))
            label_addr.setdefault(mm.group(1), addr)

        if bytes_hex is not None:
            rows.append((addr, bytes_hex, source))

    # Resolve transitive aliases (a := b, b := c -> a -> c's addr).
    for name, target in list(aliases.items()):
        seen: set[str] = {name}
        cur = target
        while cur in aliases and cur not in seen:
            seen.add(cur)
            cur = aliases[cur]
        if cur in label_addr:
            label_addr[name] = label_addr[cur]

    # Resolve the code-address set: explicit fixture wins, else the set
    # derived from the .lst's first-emit classification.
    code_addrs = fixture_code_addrs if fixture_code_addrs is not None else derived_code
    if not code_addrs:
        print("no code addresses (empty fixture and empty .lst derivation)",
              file=sys.stderr)
        return 2

    # ----- Pass 2: walk emitted rows looking for table runs ------------
    # Sort rows by address (stable) — rows already arrive in source
    # order which is monotonic in addr for code/data segments.
    # Build address -> row index for quick lookup.
    by_idx_addr: dict[int, int] = {}
    for i, (a, _, _) in enumerate(rows):
        # Multiple rows can share an address (macro line + emit line);
        # keep the first emit-row only. parse_emit_row already filtered
        # out non-emit rows, but a macro can still produce multiple
        # consecutive emits at the same addr from chained directives.
        # Use the first hit so subsequent walks find a clean stride.
        by_idx_addr.setdefault(a, i)

    pcrel_tables: list[dict] = []
    abs_tables: list[dict] = []
    bra_tables: list[dict] = []
    used_rows: set[int] = set()

    # Pre-compute the set of addresses that have at least one NAMED
    # label pinned to them (i.e., not loc_/sub_/off_/byte_/word_/
    # locret_/j_, anonymous +/-, or pure local .foo names). Used as
    # a "this address is a table base" anchor for bra-trampoline
    # detection — without this, runs of consecutive bra.s/bra.w
    # instructions inside ordinary code get misclassified as tables.
    _AUTO_PREFIX = ("loc_", "locret_", "sub_",
                    "byte_", "word_", "off_", "j_")
    table_base_addrs: set[int] = set()
    for name, name_addr in label_addr.items():
        if name.startswith(_AUTO_PREFIX): continue
        if name.startswith(("+", "-", ".")): continue
        table_base_addrs.add(name_addr)

    for i, (addr, bytes_hex, source) in enumerate(rows):
        if i in used_rows:
            continue

        # Try PCREL_W first. The base label often resolves to a macro
        # variable that AS reassigns dozens of times across the listing
        # (e.g., "current_offset_table"), so we don't trust label_addr
        # for it. Instead we treat the first row's address as the
        # table base — by disasm convention the offset-table label is
        # pinned to the first entry, so target = first_addr + offset.
        m = PCREL_W_RE.match(source)
        if m and len(bytes_hex) == 1:
            base = m.group(2)
            base_addr = addr
            entries: list[tuple[int, str]] = []
            row_idxs: list[int] = []
            cur = i
            expected_addr = addr
            while cur < len(rows):
                a2, b2, s2 = rows[cur]
                if a2 != expected_addr:
                    break
                mm = PCREL_W_RE.match(s2)
                if not mm or len(b2) != 1 or mm.group(2) != base:
                    break
                word = int(b2[0], 16)
                off = word - 0x10000 if word & 0x8000 else word
                target = (base_addr + off) & 0xFFFFFF
                if (target & 1) or target >= args.rom_max:
                    break
                if target not in code_addrs:
                    break
                entries.append((target, mm.group(1)))
                row_idxs.append(cur)
                expected_addr += 2
                cur += 1

            if len(entries) >= args.min_entries:
                pcrel_tables.append({
                    "start": addr,
                    "end":   addr + 2 * len(entries),
                    "stride": 2,
                    "format": "pcrel16",
                    "base":  base,
                    "base_addr": base_addr,
                    "entries": entries,
                })
                used_rows.update(row_idxs)
                continue

        # Then ABS_L
        m2 = ABS_L_RE.match(source)
        if m2 and len(bytes_hex) == 2:
            entries = []
            row_idxs = []
            cur = i
            expected_addr = addr
            while cur < len(rows):
                a2, b2, s2 = rows[cur]
                if a2 != expected_addr:
                    break
                mm = ABS_L_RE.match(s2)
                if not mm or len(b2) != 2:
                    break
                target = ((int(b2[0], 16) << 16) | int(b2[1], 16)) & 0xFFFFFF
                if (target & 1) or target >= args.rom_max:
                    break
                if target not in code_addrs:
                    break
                entries.append((target, mm.group(1)))
                row_idxs.append(cur)
                expected_addr += 4
                cur += 1

            if len(entries) >= args.min_entries:
                abs_tables.append({
                    "start": addr,
                    "end":   addr + 4 * len(entries),
                    "stride": 4,
                    "format": "abs",
                    "entries": entries,
                })
                used_rows.update(row_idxs)
                continue

        # Then bra.w trampoline runs (e.g. Sonic 2's GameModesArray).
        # Each entry is a 4-byte `bra.w Target` (60 00 XX XX). The
        # entry's ADDRESS is itself the dispatched function — so the
        # extracted target is the entry address, not the bra.w
        # destination. We still validate the bra.w destination is a
        # code address as a sanity check.
        #
        # Anchor the table-start to a row that has a NAMED label
        # pinned to its address (precomputed in table_base_addrs).
        # Without this, sequences of bra.w / bra.s instructions that
        # aren't tables (just ordinary code with consecutive branches)
        # get misidentified — the run would appear coherent because
        # every bra destination is a valid code address.
        m3 = BRA_W_RE.match(source)
        if m3 and len(bytes_hex) == 2 and bytes_hex[0].lower() == "6000" and addr in table_base_addrs:
            entries = []
            row_idxs = []
            cur = i
            expected_addr = addr
            while cur < len(rows):
                a2, b2, s2 = rows[cur]
                if a2 != expected_addr:
                    break
                mm = BRA_W_RE.match(s2)
                if not mm or len(b2) != 2 or b2[0].lower() != "6000":
                    break
                # Validate the bra.w destination is in-rom code (so we
                # don't mis-detect a stray `bra.w` followed by data as
                # a table).
                disp = int(b2[1], 16)
                if disp & 0x8000: disp -= 0x10000
                bra_dest = (a2 + 2 + disp) & 0xFFFFFF
                if (bra_dest & 1) or bra_dest >= args.rom_max:
                    break
                if bra_dest not in code_addrs:
                    break
                # The entry address itself is what gets dispatched
                # (the trampoline). Track the bra destination too —
                # in the recompiler's codegen the trampoline body
                # becomes a tail call to the destination function, so
                # that destination must also be a discovered function
                # entry (e.g. GM_Sega at $002E10 reached via the
                # GameModeArray trampoline at $000396).
                entries.append((a2, mm.group(1), bra_dest))
                row_idxs.append(cur)
                expected_addr += 4
                cur += 1

            if len(entries) >= args.min_entries:
                bra_tables.append({
                    "start": addr,
                    "end":   addr + 4 * len(entries),
                    "stride": 4,
                    "format": "bra_w",
                    "entries": entries,
                })
                used_rows.update(row_idxs)
                continue

        # And bra.s trampoline runs (e.g. Sonic 1's EniDec_JmpTable).
        # Each entry is 2 bytes (60 XX with XX != 00 and != FF).
        # Same named-label anchor as the bra.w branch above.
        m4 = BRA_S_RE.match(source)
        if (m4 and len(bytes_hex) == 1 and
                bytes_hex[0][:2].lower() == "60" and
                bytes_hex[0][2:].lower() not in ("00", "ff") and
                addr in table_base_addrs):
            entries = []
            row_idxs = []
            cur = i
            expected_addr = addr
            while cur < len(rows):
                a2, b2, s2 = rows[cur]
                if a2 != expected_addr:
                    break
                mm = BRA_S_RE.match(s2)
                if not mm or len(b2) != 1:
                    break
                w = b2[0].lower()
                if w[:2] != "60" or w[2:] in ("00", "ff"):
                    break
                disp = int(w[2:], 16)
                if disp & 0x80: disp -= 0x100
                bra_dest = (a2 + 2 + disp) & 0xFFFFFF
                if (bra_dest & 1) or bra_dest >= args.rom_max:
                    break
                if bra_dest not in code_addrs:
                    break
                entries.append((a2, mm.group(1), bra_dest))
                row_idxs.append(cur)
                expected_addr += 2
                cur += 1

            if len(entries) >= args.min_entries:
                bra_tables.append({
                    "start": addr,
                    "end":   addr + 2 * len(entries),
                    "stride": 2,
                    "format": "bra_s",
                    "entries": entries,
                })
                used_rows.update(row_idxs)
                continue

    # ----- Emit ---------------------------------------------------------
    args.output.parent.mkdir(parents=True, exist_ok=True)
    header = (args.header if args.header is not None
              else HEADER_DEFAULT.format(prefix=args.prefix))

    pcrel_tables.sort(key=lambda t: t["start"])
    abs_tables.sort(key=lambda t: t["start"])
    bra_tables.sort(key=lambda t: t["start"])

    targets: set[int] = set()
    target_names: dict[int, str] = {}
    for t in pcrel_tables + abs_tables:
        for addr_t, name in t["entries"]:
            targets.add(addr_t)
            target_names.setdefault(addr_t, name)
    # bra-trampoline entries are 3-tuples; seed both the entry
    # (the dispatched trampoline) AND the bra destination (the actual
    # handler the trampoline tail-calls into).
    for t in bra_tables:
        for entry_addr, name, bra_dest in t["entries"]:
            targets.add(entry_addr)
            target_names.setdefault(entry_addr, name)
            targets.add(bra_dest)
            target_names.setdefault(bra_dest, name)

    with args.output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write(f"# Tables found: {len(pcrel_tables)} pcrel16, "
                f"{len(abs_tables)} abs, {len(bra_tables)} bra-trampoline\n")
        f.write(f"# Unique targets: {len(targets)}\n\n")

        # PCREL_W tables: emit as [[jump_table]] records.
        for t in pcrel_tables:
            f.write("[[jump_table]]\n")
            f.write(f"start  = 0x{t['start'] + args.offset:06X}\n")
            f.write(f"end    = 0x{t['end'] + args.offset:06X}\n")
            f.write(f"stride = 2\n")
            f.write(f"format = \"pcrel16\"   # {t['base']} ({len(t['entries'])} entries)\n\n")

        # ABS_L tables: same shape, format = "abs".
        for t in abs_tables:
            first_name = t["entries"][0][1] if t["entries"] else ""
            f.write("[[jump_table]]\n")
            f.write(f"start  = 0x{t['start'] + args.offset:06X}\n")
            f.write(f"end    = 0x{t['end'] + args.offset:06X}\n")
            f.write(f"stride = 4\n")
            f.write(f"format = \"abs\"   # {len(t['entries'])} entries, first={first_name}\n\n")

        # bra.w / bra.s trampoline runs ARE jump tables: the dispatch JMP
        # at the source site lands on the trampoline body itself (which
        # then bra's onward to the real handler). The recompiler reads
        # the bra_w / bra_s formats and treats each entry as its own
        # function. The bra destinations are also added to
        # [functions].extra below so the trampoline tail-call resolves.
        for t in bra_tables:
            first_name = t["entries"][0][1] if t["entries"] else ""
            f.write("[[jump_table]]\n")
            f.write(f"start  = 0x{t['start'] + args.offset:06X}\n")
            f.write(f"end    = 0x{t['end'] + args.offset:06X}\n")
            f.write(f"stride = {t['stride']}\n")
            f.write(f"format = \"{t['format']}\"   # {len(t['entries'])} entries, first={first_name}\n\n")

        # Targets: flat array under [functions].extra.
        f.write("[functions]\n")
        f.write("extra = [\n")
        for a in sorted(targets):
            f.write(f"    0x{a + args.offset:06X},   # {target_names[a]}\n")
        f.write("]\n")

    print(
        f"gen_disasm_jumptables: {len(pcrel_tables)} pcrel16 + "
        f"{len(abs_tables)} abs + {len(bra_tables)} bra tables, "
        f"{len(targets)} unique targets -> {args.output}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
